"""Private, per-user retrieval-augmented generation using Supabase pgvector.

Embeddings are generated by Gemini Embedding 001 at 768 dimensions. Retrieved chunks
are always constrained to the user ID derived from a validated Supabase bearer token.
If embeddings are unavailable, retrieval degrades to a per-user keyword search, never
an unauthenticated/global search.
"""
from __future__ import annotations

import logging
import os
import re
from typing import Any, Dict, List, Optional

import httpx
from dotenv import load_dotenv

from storage_service import get_supabase_client

load_dotenv()
load_dotenv(os.path.join(os.path.dirname(__file__), ".env"), override=False)

logger = logging.getLogger("aarogya.rag")
EMBEDDING_MODEL = os.getenv("GEMINI_EMBEDDING_MODEL", "gemini-embedding-001")
EMBEDDING_DIMENSIONS = 768
CHUNK_SIZE = max(700, min(int(os.getenv("RAG_CHUNK_SIZE", "1400")), 2200))
CHUNK_OVERLAP = max(100, min(int(os.getenv("RAG_CHUNK_OVERLAP", "200")), CHUNK_SIZE // 3))
TOP_K = max(1, min(int(os.getenv("RAG_TOP_K", "5")), 8))
MIN_SIMILARITY = float(os.getenv("RAG_MIN_SIMILARITY", "0.20"))

_RAG_HTTP_CLIENT: Optional[httpx.Client] = None


def get_rag_http_client() -> httpx.Client:
    global _RAG_HTTP_CLIENT
    if _RAG_HTTP_CLIENT is None or _RAG_HTTP_CLIENT.is_closed:
        _RAG_HTTP_CLIENT = httpx.Client(
            timeout=httpx.Timeout(6.0, connect=3.0),
            limits=httpx.Limits(max_keepalive_connections=10, max_connections=20, keepalive_expiry=60.0),
        )
    return _RAG_HTTP_CLIENT


class RagUnavailableError(RuntimeError):
    pass


def _embed(text: str, task_type: str) -> List[float]:
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        raise RagUnavailableError("GEMINI_API_KEY is required to generate document embeddings.")
    embed_config = {
        "taskType": task_type,
        "outputDimensionality": EMBEDDING_DIMENSIONS,
    }
    if task_type == "RETRIEVAL_DOCUMENT":
        embed_config["title"] = "Aarogya personal medical record"
    payload = {
        "model": f"models/{EMBEDDING_MODEL}",
        "content": {"parts": [{"text": text[:12000]}]},
        "embedContentConfig": embed_config,
    }
    client = get_rag_http_client()
    try:
        response = client.post(
            f"https://generativelanguage.googleapis.com/v1beta/models/{EMBEDDING_MODEL}:embedContent",
            headers={"x-goog-api-key": api_key, "Content-Type": "application/json"},
            json=payload,
            timeout=httpx.Timeout(6.0, connect=3.0),
        )
        if response.status_code >= 400:
            logger.warning("Embedding request failed: status=%s model=%s", response.status_code, EMBEDDING_MODEL)
            raise RagUnavailableError(f"Embedding provider returned HTTP {response.status_code}.")
        values = response.json().get("embedding", {}).get("values")
        if not isinstance(values, list) or len(values) != EMBEDDING_DIMENSIONS:
            raise RagUnavailableError("Embedding provider returned an unexpected vector size.")
        return [float(value) for value in values]
    except (httpx.HTTPError, ValueError, TypeError) as exc:
        if isinstance(exc, RagUnavailableError):
            raise
        raise RagUnavailableError("Embedding provider request failed.") from exc


def _vector_literal(values: List[float]) -> str:
    return "[" + ",".join(f"{value:.8f}" for value in values) + "]"


def chunk_text(text: str) -> List[str]:
    normalized = re.sub(r"[ \t]+", " ", text.replace("\x00", " ")).strip()
    if not normalized:
        return []
    # Prefer paragraph/sentence boundaries, then fall back to a hard split.
    chunks: List[str] = []
    start = 0
    while start < len(normalized):
        end = min(start + CHUNK_SIZE, len(normalized))
        if end < len(normalized):
            candidates = [normalized.rfind("\n", start, end), normalized.rfind(". ", start, end), normalized.rfind("; ", start, end)]
            boundary = max(candidates)
            if boundary > start + int(CHUNK_SIZE * 0.55):
                end = boundary + 1
        piece = normalized[start:end].strip()
        if piece:
            chunks.append(piece)
        if end >= len(normalized):
            break
        start = max(start + 1, end - CHUNK_OVERLAP)
    return chunks


def _document_text(row: Dict[str, Any]) -> str:
    extracted = row.get("extracted_fields") or {}
    if not isinstance(extracted, dict):
        extracted = {}
    summary = row.get("ai_summary") or {}
    if not isinstance(summary, dict):
        summary = {"en": str(summary)}
    sections = [
        f"Document: {row.get('title') or ''}",
        f"Type: {row.get('document_type') or ''}",
        f"Report date: {row.get('visit_date') or ''}",
        f"Facility: {row.get('facility_name') or ''}",
        f"Doctor: {extracted.get('doctor_name') or ''}",
        f"Source text:\n{extracted.get('raw_ocr_text') or ''}",
        "Medicines:\n" + __import__("json").dumps(extracted.get("medicines") or [], ensure_ascii=False),
        "Lab values:\n" + __import__("json").dumps(extracted.get("lab_values") or [], ensure_ascii=False),
        f"Summary:\n{summary.get('en') or ''}",
        f"Review alerts:\n{row.get('review_alerts') or []}",
    ]
    return "\n".join(section for section in sections if section and not section.endswith(": "))


def index_medical_document(user_id: str, document_id: str) -> Dict[str, Any]:
    client = get_supabase_client()
    if not client:
        raise RagUnavailableError("Supabase service is not configured on the backend.")
    result = (
        client.table("medical_documents")
        .select("id,patient_id,title,document_type,visit_date,facility_name,ai_summary,extracted_fields,review_alerts")
        .eq("id", document_id)
        .eq("patient_id", user_id)
        .limit(1)
        .execute()
    )
    rows = result.data or []
    if not rows:
        raise PermissionError("The document was not found for the authenticated user.")
    row = rows[0]
    full_text = _document_text(row)
    chunks = chunk_text(full_text)
    if not chunks:
        raise ValueError("The document has no extractable text to index.")
    if len(chunks) > 60:
        chunks = chunks[:60]

    rows_to_upsert = []
    for index, content in enumerate(chunks):
        embedding = _embed(content, "RETRIEVAL_DOCUMENT")
        rows_to_upsert.append({
            "patient_id": user_id,
            "document_id": document_id,
            "chunk_index": index,
            "content": content,
            "embedding": _vector_literal(embedding),
            "metadata": {
                "title": row.get("title") or "Medical document",
                "document_type": row.get("document_type") or "",
                "visit_date": str(row.get("visit_date") or ""),
            },
        })

    # Upsert first, then remove stale tail chunks, so a failed embed does not erase an existing index.
    client.table("medical_document_chunks").upsert(rows_to_upsert, on_conflict="document_id,chunk_index").execute()
    client.table("medical_document_chunks").delete().eq("patient_id", user_id).eq("document_id", document_id).gte("chunk_index", len(rows_to_upsert)).execute()
    return {"document_id": document_id, "chunks_indexed": len(rows_to_upsert), "embedding_model": EMBEDDING_MODEL, "dimensions": EMBEDDING_DIMENSIONS}



def reindex_user_documents(user_id: str) -> Dict[str, Any]:
    """Reindex all existing documents belonging to the authenticated user (no cross-user scan)."""
    client = get_supabase_client()
    if not client:
        raise RagUnavailableError("Supabase service is not configured on the backend.")
    response = client.table("medical_documents").select("id").eq("patient_id", user_id).order("created_at", desc=True).limit(100).execute()
    document_ids = [str(row.get("id")) for row in (response.data or []) if row.get("id")]
    indexed = 0
    failures: List[Dict[str, str]] = []
    for document_id in document_ids:
        try:
            index_medical_document(user_id, document_id)
            indexed += 1
        except Exception as exc:
            logger.warning("One document could not be reindexed: document_id=%s error_type=%s", document_id, type(exc).__name__)
            failures.append({"document_id": document_id, "reason": "Indexing failed; retry after checking API quota and document content."})
    return {"total_documents": len(document_ids), "indexed_documents": indexed, "failed_documents": failures}

def _lexical_retrieval(user_id: str, query: str, limit: int) -> List[Dict[str, Any]]:
    client = get_supabase_client()
    if not client:
        raise RagUnavailableError("Supabase service is not configured on the backend.")
    response = (
        client.table("medical_documents")
        .select("id,patient_id,title,document_type,visit_date,facility_name,ai_summary,extracted_fields,review_alerts")
        .eq("patient_id", user_id)
        .order("created_at", desc=True)
        .limit(75)
        .execute()
    )
    terms = {t for t in re.findall(r"[\w-]{3,}", query.casefold()) if t not in {
        "the", "and", "for", "what", "does", "about", "have", "from", "with", "your", "can", "you", "please", "tell", "explain", "this", "that", "are", "was", "were", "how"
    }}
    candidates = []
    for row in response.data or []:
        content = _document_text(row)
        text_terms = set(re.findall(r"[\w-]{3,}", content.casefold()))
        overlap = len(terms & text_terms)
        if not terms:
            overlap = 1
        if overlap > 0:
            candidates.append({
                "document_id": row["id"],
                "document_title": row.get("title") or "Medical document",
                "document_date": str(row.get("visit_date") or ""),
                "content": content[:2200],
                "similarity": min(0.45, overlap / max(1, len(terms))),
                "retrieval_mode": "keyword_fallback",
            })
    candidates.sort(key=lambda item: item["similarity"], reverse=True)
    return candidates[:limit]


def _is_conversational_query(query: str) -> bool:
    q = query.strip().casefold()
    conversational = {
        "hi", "hello", "hey", "hola", "namaste", "vanakkam", "namaskaram",
        "good morning", "good afternoon", "good evening", "good night",
        "how are you", "who are you", "what can you do", "what is aarogya",
        "tell me about yourself", "help", "thanks", "thank you", "bye", "goodbye"
    }
    return q in conversational or len(q) < 4


def retrieve_relevant_chunks(user_id: str, query: str, limit: int = TOP_K) -> Dict[str, Any]:
    """Return only chunks owned by user_id, with lexical fallback if vector search fails."""
    # Fast path 1: conversational greetings never require scanning medical documents
    if _is_conversational_query(query):
        return {"hits": [], "mode": "conversational"}

    client = get_supabase_client()
    if not client:
        raise RagUnavailableError("Supabase service is not configured on the backend.")

    # Fast path 2: verify the user has any medical records before invoking embedding models
    try:
        doc_check = client.table("medical_documents").select("id").eq("patient_id", user_id).limit(1).execute()
        if not (doc_check.data and len(doc_check.data) > 0):
            return {"hits": [], "mode": "no_documents"}
    except Exception as exc:
        logger.warning("Document pre-check failed: error_type=%s", type(exc).__name__)

    try:
        query_vector = _embed(query, "RETRIEVAL_QUERY")
        response = client.rpc("match_aarogya_document_chunks", {
            "query_embedding": _vector_literal(query_vector),
            "match_count": max(1, min(limit, 8)),
            "min_similarity": MIN_SIMILARITY,
            "filter_patient_id": user_id,
        }).execute()
        matches = response.data or []
        hits = [{
            "document_id": item["document_id"],
            "document_title": item.get("document_title") or "Medical document",
            "document_date": str(item.get("document_date") or ""),
            "content": item.get("content") or "",
            "similarity": float(item.get("similarity") or 0.0),
            "retrieval_mode": "vector",
        } for item in matches]
        if hits:
            return {"hits": hits, "mode": "vector"}
    except Exception as exc:
        # Quota, disabled embeddings, or an un-applied schema migration should not expose data;
        # fallback still queries only medical_documents filtered by the verified user id.
        logger.warning("Vector retrieval unavailable; using lexical search: error_type=%s", type(exc).__name__)

    hits = _lexical_retrieval(user_id, query, max(1, min(limit, 8)))
    return {"hits": hits, "mode": "keyword_fallback" if hits else "no_match"}


def format_context_and_citations(hits: List[Dict[str, Any]]) -> tuple[str, List[Dict[str, Any]]]:
    excerpts = []
    citations = []
    for index, hit in enumerate(hits, start=1):
        source = f"S{index}"
        excerpts.append(
            f"[{source}] {hit.get('document_title', 'Medical document')} | Date: {hit.get('document_date') or 'not recorded'}\n"
            f"Relevant excerpt: {hit.get('content', '')[:2400]}"
        )
        citations.append({
            "source": source,
            "recordId": hit.get("document_id"),
            "documentTitle": hit.get("document_title", "Medical document"),
            "documentDate": hit.get("document_date") or "",
            "similarity": round(float(hit.get("similarity") or 0.0), 3),
        })
    return "\n\n".join(excerpts), citations
